sonar.projectKey=swiss-ai_model-launch
sonar.organization=swiss-ai

sonar.sources=src
sonar.tests=tests

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=legacy/**,**/__pycache__/**,**/*.egg-info/**,.venv/**,docs/**,site/**

sonar.sourceEncoding=UTF-8
