#!/usr/bin/env bash
# Generated by model-launch-factory run 3a1dee3df6e841cfa25115d5cb5dfe74 on 2026-09-24
# Gate: probe + streaming passed; advisory: core 11/13 (core_assistant_prefill, core_determinism); multimodal 4/8 (mm_audio_small, mm_audio_large, mm_interleaved, mm_no_degeneration_hard_audio)
# Full mcs report, evals and benchmarks: see mcs/, evals/, benchmarks/ next to this file.
# This is the exact `sml advanced` form the factory verified: `sml advanced` has no
# --model flag; the weights come from the capstor registry via --framework-args.
set -euo pipefail
sml advanced \
  --system clariden \
  --partition highprio \
  --framework vllm \
  --served-model-name XiaomiMiMo/MiMo-V2.6-Pro-RL-vllm \
  --replicas 1 \
  --nodes-per-replica 4 \
  --time 03:00:00 \
  --environment src/swiss_ai_model_launch/assets/envs/vllm_xiaomimimo__mimo-v2.6-pro-rl.toml \
  --framework-args "--model /capstor/store/cscs/swissai/infra01/hf_models/models/XiaomiMiMo/MiMo-V2.6-Pro-RL --tensor-parallel-size 4 --pipeline-parallel-size 4 --max-model-len 262144 --gpu-memory-utilization 0.85 --reasoning-parser mimo --tool-call-parser mimo --enable-auto-tool-choice --trust-remote-code"
