name: open_loop_decode
executor: ramping-arrival-rate
startRate: 2
timeUnit: 1s
stages:
  - duration: 3m
    target: 2
  - duration: 3m
    target: 3
  - duration: 3m
    target: 4
  - duration: 3m
    target: 5
preAllocatedVUs: 800
maxVUs: 1600
think_time: "0"
max_tokens: "512"
request_timeout: 600s
ignore_eos: true
prompt_labels:
  - short
  - medium
