name: spike
executor: ramping-vus
startVUs: 0
stages:
  - duration: 1m
    target: 10
  - duration: 30s
    target: 100
  - duration: 3m
    target: 100
  - duration: 30s
    target: 10
  - duration: 3m
    target: 10
  - duration: 30s
    target: 0
gracefulRampDown: 30s
think_time: "0"
max_tokens: "4096"
