#!/usr/bin/env bash
# Generated by model-launch-factory run 1a8830a75513461a88cd6f99d3653ebc on 2026-09-24
# Gate: probe + streaming passed; advisory: core 12/13 (core_assistant_prefill)
# Full mcs report, evals and benchmarks: see mcs/, evals/, benchmarks/ next to this file.
# This is the exact `sml advanced` form the factory verified: `sml advanced` has no
# --model flag; the weights come from the capstor registry via --framework-args.
set -euo pipefail
sml advanced \
  --system clariden \
  --partition highprio \
  --framework vllm \
  --served-model-name zai-org/GLM-5.3-vllm \
  --replicas 1 \
  --nodes-per-replica 4 \
  --time 03:00:00 \
  --environment src/swiss_ai_model_launch/assets/envs/vllm_zai-org__glm-5.3.toml \
  --framework-args "--model /capstor/store/cscs/swissai/infra01/hf_models/models/zai-org/GLM-5.3 --tensor-parallel-size 16 --max-model-len 262144 --max-num-seqs 32 --reasoning-parser glm47 --tool-call-parser glm47 --enable-auto-tool-choice"
