#!/usr/bin/env bash
# Generated by model-launch-factory run 537f0b17fb7143448ad07ff29cdf9352 on 2026-09-28
# Gate: probe + streaming passed; advisory: core 11/13 (core_system, core_multi_system)
# Full mcs report, evals and benchmarks: see mcs/, evals/, benchmarks/ next to this file.
# This is the exact `sml advanced` form the factory verified: `sml advanced` has no
# --model flag; the weights come from the capstor registry via --framework-args.
set -euo pipefail
sml advanced \
  --system clariden \
  --framework vllm \
  --served-model-name HuggingFaceTB/SmolLM2-135M-Instruct-vllm \
  --replicas 1 \
  --nodes-per-replica 1 \
  --time 03:00:00 \
  --environment src/swiss_ai_model_launch/assets/envs/vllm_0.30.0.toml \
  --framework-args "--model /capstor/store/cscs/swissai/infra01/hf_models/models/HuggingFaceTB/SmolLM2-135M-Instruct --tensor-parallel-size 1"
