#!/usr/bin/env bash
# Generated by model-launch-factory run c52187a88edc48a2aa366a8e7a21770f on 2026-09-15
# Gate: probe + streaming passed; advisory: core 11/13 (core_system, core_multi_system)
# Full mcs report, evals and benchmarks: see mcs/, evals/, benchmarks/ next to this file.
set -euo pipefail
sml advanced \
  --system clariden \
  --partition debug \
  --model HuggingFaceTB/SmolLM2-135M-Instruct \
  --framework vllm \
  --replicas 1 \
  --nodes-per-replica 1 \
  --time 00:20:00 \
  --framework-args "--tensor-parallel-size 1"
