#!/usr/bin/env bash
# Generated by model-launch-factory run 6d321ba9cf6b4b0dbbb3eef7ea75fc0a on 2026-09-15
# Gate: probe + streaming passed
# Full mcs report, evals and benchmarks: see mcs/, evals/, benchmarks/ next to this file.
set -euo pipefail
sml advanced \
  --system clariden \
  --partition normal \
  --model HuggingFaceTB/SmolLM2-135M-Instruct \
  --framework vllm \
  --replicas 1 \
  --nodes-per-replica 1 \
  --time 04:00:00 \
  --framework-args "--tensor-parallel-size 4"
