#!/usr/bin/env bash
# Generated by model-launch-factory run 22d2152ffa864626af00e43defea905d on 2026-09-23
# Gate: probe + streaming passed; advisory: core 11/13 (core_assistant_prefill, core_determinism); multimodal 4/8 (mm_audio_small, mm_audio_large, mm_interleaved, mm_no_degeneration_hard_audio)
# Full mcs report, evals and benchmarks: see mcs/, evals/, benchmarks/ next to this file.
# This is the exact `sml advanced` form the factory verified: `sml advanced` has no
# --model flag; the weights come from the capstor registry via --framework-args.
set -euo pipefail
sml advanced \
  --system clariden \
  --partition highprio \
  --framework vllm \
  --served-model-name deepseek-ai/DeepSeek-V4.1-Flash-vllm \
  --replicas 1 \
  --nodes-per-replica 2 \
  --time 03:00:00 \
  --environment src/swiss_ai_model_launch/assets/envs/vllm_0.30.0.toml \
  --framework-args "--model /capstor/store/cscs/swissai/infra01/hf_models/models/deepseek-ai/DeepSeek-V4.1-Flash --tensor-parallel-size 8 --reasoning-parser deepseek_v41"
