#!/usr/bin/env bash
# Generated by model-launch-factory run ffd73be628bc47769271fc492040427f on 2026-09-15
# Gate: probe + streaming passed; advisory: core 9/13 (core_system, core_tokenizer_roundtrip, core_tokenizer_unicode, core_multi_system)
# Full mcs report, evals and benchmarks: see mcs/, evals/, benchmarks/ next to this file.
set -euo pipefail
sml advanced \
  --system clariden \
  --partition debug \
  --model HuggingFaceTB/SmolLM2-135M-Instruct \
  --framework sglang \
  --replicas 1 \
  --nodes-per-replica 1 \
  --time 00:20:00 \
  --framework-args "--tp-size 1"
