#!/usr/bin/env bash
# Generated by model-launch-factory run f695f533a7654b47b335820f94cf9be9 on 2026-09-15
# Gate: probe + streaming passed
# Full mcs report, evals and benchmarks: see mcs/, evals/, benchmarks/ next to this file.
set -euo pipefail
sml advanced \
  --system clariden \
  --partition normal \
  --model HuggingFaceTB/SmolLM2-135M-Instruct \
  --framework sglang \
  --replicas 1 \
  --nodes-per-replica 1 \
  --time 04:00:00 \
  --framework-args "--tp-size 4"
