#!/usr/bin/env bash
# Generated by model-launch-factory run 5c05920ff96a490098cc752ec5b14616 on 2026-09-24
# Gate: probe + streaming passed; advisory: core 11/13 (core_assistant_prefill, core_determinism)
# Full mcs report, evals and benchmarks: see mcs/, evals/, benchmarks/ next to this file.
# This is the exact `sml advanced` form the factory verified: `sml advanced` has no
# --model flag; the weights come from the capstor registry via --framework-args.
set -euo pipefail
sml advanced \
  --system clariden \
  --partition highprio \
  --framework vllm \
  --served-model-name XiaomiMiMo/MiMo-V2.6-Flash-RL-vllm \
  --replicas 1 \
  --nodes-per-replica 1 \
  --time 03:00:00 \
  --environment src/swiss_ai_model_launch/assets/envs/vllm_nightly-7f1a5398e9610d96c473931a26c0e12bbe0d0423.toml \
  --framework-args "--model /capstor/store/cscs/swissai/infra01/hf_models/models/XiaomiMiMo/MiMo-V2.6-Flash-RL --tensor-parallel-size 4 --reasoning-parser mimo --tool-call-parser mimo --enable-auto-tool-choice --trust-remote-code"
