image = "/iopsstor/scratch/cscs/edebened/ce-images/large_model_serving.sqsh"

mounts = [
  "/iopsstor/store/cscs/swissai/a09/xyao/bin:/ocfbin",
  "/capstor",
  "/iopsstor",
  "/usr/lib64/libhwloc.so.15:/usr/lib/libhwloc.so.15",
  "/usr/lib64/libpciaccess.so.0:/usr/lib/libpciaccess.so.0",
  "/usr/lib64/libxml2.so.2:/usr/lib/libxml2.so.2",
]

workdir = "/opt"

[env]
NCCL_NET = "Socket"
NCCL_SOCKET_IFNAME = "hsn"

[annotations]
com.hooks.cxi.enabled = "false"
