name: Lightweight CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Tests (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    env:
      SML_CSCS_API_KEY: ${{ secrets.SML_CSCS_API_KEY }}
      SML_FIRECREST_CLIENT_ID: ${{ secrets.SML_FIRECREST_CLIENT_ID }}
      SML_FIRECREST_CLIENT_SECRET: ${{ secrets.SML_FIRECREST_CLIENT_SECRET }}
      SML_FIRECREST_SYSTEM: ${{ secrets.SML_FIRECREST_SYSTEM }}
      SML_FIRECREST_TOKEN_URI: ${{ secrets.SML_FIRECREST_TOKEN_URI }}
      SML_FIRECREST_URL: ${{ secrets.SML_FIRECREST_URL }}
      SML_PARTITION: ${{ secrets.SML_PARTITION }}
      SML_RESERVATION: ${{ secrets.SML_RESERVATION }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
      - run: make _test-lightweight
