name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, labeled]
  workflow_dispatch:

jobs:
  static-checks:
    uses: ./.github/workflows/static.yml

  docker:
    needs: [static-checks]
    uses: ./.github/workflows/docker.yml
    permissions:
      contents: read
      packages: write
    secrets: inherit

  test-lightweight:
    name: Integration Tests (lightweight)
    needs: [docker]
    if: needs.docker.result == 'success'
    runs-on: ubuntu-latest
    env:
      SML_CSCS_API_KEY: ${{ secrets.SML_CSCS_API_KEY }}
      SML_FIRECREST_CLIENT_ID: ${{ secrets.SML_FIRECREST_CLIENT_ID }}
      SML_FIRECREST_CLIENT_SECRET: ${{ secrets.SML_FIRECREST_CLIENT_SECRET }}
      SML_FIRECREST_SYSTEM: ${{ secrets.SML_FIRECREST_SYSTEM }}
      SML_FIRECREST_TOKEN_URI: ${{ secrets.SML_FIRECREST_TOKEN_URI }}
      SML_FIRECREST_URL: ${{ secrets.SML_FIRECREST_URL }}
      SML_PARTITION: ${{ secrets.SML_PARTITION }}
      SML_RESERVATION: ${{ secrets.SML_RESERVATION }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
        with:
          python-version: "3.12"
      - run: make _test-lightweight

  test-medium:
    name: Integration Tests (medium)
    needs: [docker]
    if: |
      needs.docker.result == 'success' &&
      (github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'requires-medium-tests'))
    runs-on: ubuntu-latest
    env:
      SML_CSCS_API_KEY: ${{ secrets.SML_CSCS_API_KEY }}
      SML_FIRECREST_CLIENT_ID: ${{ secrets.SML_FIRECREST_CLIENT_ID }}
      SML_FIRECREST_CLIENT_SECRET: ${{ secrets.SML_FIRECREST_CLIENT_SECRET }}
      SML_FIRECREST_SYSTEM: ${{ secrets.SML_FIRECREST_SYSTEM }}
      SML_FIRECREST_TOKEN_URI: ${{ secrets.SML_FIRECREST_TOKEN_URI }}
      SML_FIRECREST_URL: ${{ secrets.SML_FIRECREST_URL }}
      SML_PARTITION: ${{ secrets.SML_PARTITION }}
      SML_RESERVATION: ${{ secrets.SML_RESERVATION }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
        with:
          python-version: "3.12"
      - run: make _test-medium

  test-comprehensive:
    name: Integration Tests (comprehensive)
    needs: [docker]
    if: |
      needs.docker.result == 'success' &&
      (github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'requires-full-tests'))
    runs-on: ubuntu-latest
    env:
      SML_CSCS_API_KEY: ${{ secrets.SML_CSCS_API_KEY }}
      SML_FIRECREST_CLIENT_ID: ${{ secrets.SML_FIRECREST_CLIENT_ID }}
      SML_FIRECREST_CLIENT_SECRET: ${{ secrets.SML_FIRECREST_CLIENT_SECRET }}
      SML_FIRECREST_SYSTEM: ${{ secrets.SML_FIRECREST_SYSTEM }}
      SML_FIRECREST_TOKEN_URI: ${{ secrets.SML_FIRECREST_TOKEN_URI }}
      SML_FIRECREST_URL: ${{ secrets.SML_FIRECREST_URL }}
      SML_PARTITION: ${{ secrets.SML_PARTITION }}
      SML_RESERVATION: ${{ secrets.SML_RESERVATION }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
        with:
          python-version: "3.12"
      - run: make _test-comprehensive
