name: Static Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, labeled]
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    name: Python Lint & Format (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12", "3.14"]
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
      - run: make lint

  typecheck:
    name: Python Type Check (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12", "3.14"]
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
      - run: make mypy

  shellcheck:
    name: Shell Scripts Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: make shellcheck

  dockerlint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: make dockerlint

  markdownlint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: make markdownlint

  tomlfmt:
    name: TOML Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install taplo
        run: curl -fsSL https://github.com/tamasfe/taplo/releases/download/0.9.3/taplo-full-linux-x86_64.gz | gzip -d > taplo && chmod +x taplo && sudo mv taplo /usr/local/bin/taplo
      - run: make tomlfmt

  prettier:
    name: JSON & YAML Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: make prettier
